# These are enabled for ALL repositories
# They should be fast, and fix real situations.
# They should always succeed (no linters) unless there is an actual issue (no noise).
# They should only be opinionated in ways everyone can agree on
#   (I am not trying to reformat anyone's files.)
# They should not be language-specific. (Maybe??)
default_stages: [pre-commit]
repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.27.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: ^vendor/
      - id: trailing-whitespace
        exclude: '^(vendor/)|(.*\.ambr$)|^(patches/)'
      - id: no-commit-to-branch  # default: master,main
      # syntax verifiers
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        exclude: '^(chart)|(charts)|(templates)|(tests/data)/'
        args: ['--allow-multiple-documents']

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: forbid-binary
        exclude: '^(.git-crypt\/)|(vendor\/)|(charts\/.*.tgz)|(docs\/.*.png)'

  - repo: https://github.com/rmartine-ias/auto-jira-commit
    rev: v1.2.6
    hooks:
      - id: auto-jira-commit

  - repo: https://github.com/hugoh/pre-commit-fish.git
    rev: v1.2
    hooks:
      - id: fish_syntax

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.2.1
    hooks:
      - id: editorconfig-checker
        alias: ec
