extends: default
ignore-from-file: .gitignore
# https://yamllint.readthedocs.io/en/stable/rules.html
# https://github.com/ContainerSolutions/kubernetes-examples/blob/master/.yamllint
rules:
  braces: enable
  brackets: enable
  colons: enable
  commas: enable
  comments:
    level: warning
  comments-indentation:
    level: warning
  document-end: disable
  document-start: disable
  hyphens: enable
  new-line-at-end-of-file: enable
  new-lines: enable
  trailing-spaces: enable
  indentation: enable
  key-duplicates: enable
  line-length: disable
  truthy: disable
  # braces:
    # min-spaces-inside: 1
    # max-spaces-inside: 1

# vim: ft=yaml
