[tool.ruff]
# https://beta.ruff.rs/docs/rules/
# https://beta.ruff.rs/docs/settings

select = [
 "A",
 "ANN", # flake8-annotations
 "ARG",
 "ASYNC", # flake8-async
 "B",
 "C4",
 "C90", # mccabe
 "E",
 "ERA",
 "EXE",
 "F",   # pyflakes
 "I",   # isort
 "ICN",
 "INP",
 "ISC",
 "N",   # pep8-naming
 "PIE",
 "PLC",
 "PLE",
 "PLR",
 "PLW",
 "PTH",
 "RET",
 "RUF",
 "S",   # flake8-bandit
 "SIM",
 "TCH",
 "TID",
 "UP",  # pyupgrade
 "YTT", # flake8-2020
 "W", # pycodestyle
]

ignore = [
    # E501 line too long
    # pydocstyle rules to ensure docstring exists (I know already)
    "E501",
    # ANN101 self does not need to be typed
    "ANN101",
    # No required docstrings
    "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107",
    # S607 relative path to binary
    # S603 https://github.com/astral-sh/ruff/issues/4045
    "S607", "S603",
]

target-version = "py314"
